{
 "title": "mdf",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "首次渲染",
   "type": "graph",
   "description": "First content render",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "avg_over_time({job=\"apm\"} | json | line_format \"{{.apm_fcp}}\" != \"-\"  | unwrap apm_fcp [1m]) by (apm_app)",
     "legendFormat": "{{apm_app}}"
    }
   ]
  },
  {
   "title": "首字节",
   "type": "graph",
   "description": "Time to first byte",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "avg_over_time({job=\"apm\"} | json | line_format \"{{.apm_ttfb}}\" != \"-\"  | unwrap apm_ttfb [1m]) by (apm_app)",
     "legendFormat": "{{apm_app}}"
    }
   ]
  },
  {
   "title": "首屏",
   "type": "graph",
   "description": "LCP 最大渲染内容变动",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "avg_over_time({job=\"apm\"} | json | line_format \"{{.apm_lcp}}\" != \"-\"  | unwrap apm_lcp [1m]) by (apm_app)",
     "legendFormat": "{{apm_app}}"
    }
   ]
  },
  {
   "title": "慢资源",
   "type": "graph",
   "description": "一个项目中加载耗时最长的资源",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "avg_over_time({job=\"apm\"} |= \"apm_lgrscload\" | json | line_format \"{{.apm_lgrscload}}\" != \"-\" != \"undefined\" | unwrap apm_lgrscload [1m]) by (apm_lgrsc)",
     "legendFormat": "{{apm_lgrsc}}"
    }
   ]
  }
 ]
}